ENV["G5_CLIENT_UID"] ||= "spec/support/client.html"
ENV["HEROKU_APP_NAME"] ||= "g5-ch-default"
ENV["WIDGET_GARDEN_URL"] ||= "http://g5-widget-garden.herokuapp.com"
ENV["THEME_GARDEN_URL"] ||= "http://g5-theme-garden.herokuapp.com"
ENV["LAYOUT_GARDEN_URL"] ||= "http://g5-layout-garden.herokuapp.com"
